/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SignatureOptions {
  minSize: number
  avgSize: number
  maxSize: number
}
/** Writes calculated signature for `source` to the `dest`. */
export function writeBinarySignature(source: string, dest: string, options?: SignatureOptions | undefined | null): void
export function writeCloudSignature(source: string, dest: string, options?: SignatureOptions | undefined | null): void
/** Returns calculated signature of the `source`. */
export function signature(source: string, options?: SignatureOptions | undefined | null): Buffer
/** Generates a diff that transforms `source` to `target`. */
export function diff(source: string, target: string, dest: string, options?: SignatureOptions | undefined | null): void
/** Generates a diff that transforms `source` to `target. Only source signature is required. */
export function diffUsingSourceSignature(sourceSig: string, target: string, dest: string): void
/**
 * Downloads the required parts of the file and builds a new file based on `target_sig` and the
 * `source`.
 */
export function pullUsingRemoteSignature(source: string, targetSig: string, fileUri: string, dest: string): void
/** Applies `diff` to the `a` and writes the result to `result`. */
export function apply(diff: string, a: string, result: string): void
